name: CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  # TODO: unit tests should not need a database!
  UnitTest:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:root@localhost:3306/main

    steps:
      - run: sudo systemctl start mysql.service
      - run: |
          mysql -e 'CREATE DATABASE main;' --user=root --password=root
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci && npm i -g tsx
      - run: npx prisma db push
      - run: cd api/src/dev && npx tsx api-data-sync && cd ../../..
      - run: npm run test:unit:coverage

  BrowserTest:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        project: [chromium, chrome, edge, firefox, webkit]
    env:
      DATABASE_URL: mysql://root:root@localhost:3306/main
      PUBLIC_PFB_DISCORD_LINK: https://discord.gg/xCadnCRC9f
      PUBLIC_PFB_GITHUB_LINK: https://github.com/polyflowbuilder/polyflowbuilder
      PUBLIC_PFB_ANALYTICS_ID:
      DOMAIN: localhost:4173

    steps:
      - run: sudo systemctl start mysql.service
      - run: |
          mysql -e 'CREATE DATABASE main;' --user=root --password=root
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci && npm i -g tsx
      - run: npx playwright install --with-deps ${{ matrix.project }}
      - run: npx prisma db push
      - run: cd api/src/dev && npx tsx api-data-sync && cd ../../..
      - run: npm run test:${{ matrix.project }}
