name: CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  Unit Test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:root@localhost:3306/main

    steps:
      - run: sudo systemctl start mysql.service
      - run: |
        mysql -e 'CREATE DATABASE main;' -u root -p root
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit:coverage