name: Unit Test

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    name: Unit Test (Vitest)
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: install deps
        run: npm ci

      - name: unit test
        run: npm run test:unit:coverage
